### ISSUE TITLE
21/04/2023: Tổng hợp file workflow và push lên github

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#100]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1EDGYjE39La9FXoB9YV9Ss-txiGaQEWSr/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
