### ISSUE TITLE
17/03/2023: Tìm hiểu và test API lấy danh sách project

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#11]

**Comment by NoahSavant** [comment]
Hoàn thành task 4
Link document: https://docs.google.com/document/d/1tjKa5ZXiFRgabZYhzlR-SPxTKlTu9Nmt/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true

**Comment by NoahSavant** [comment]
Hoàn thành task 4
Link document: https://docs.google.com/document/d/1tjKa5ZXiFRgabZYhzlR-SPxTKlTu9Nmt/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
