### ISSUE TITLE
22/04/2023: Xây dựng thông tin các rủi ro về thay đổi yêu cầu dự án cho phần rủi ro về quản lý

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#111]

**Comment by NoahSavant** [comment]
Hoàn thành task 5
Link document: https://docs.google.com/document/d/1ligqh4QvOBsu5Evd_HSLG9XYTHcZ-ymRec8nZhpv4Y4/edit?usp=sharing

**Comment by NoahSavant** [comment]
Hoàn thành task 5
Link document: https://docs.google.com/document/d/1GHJFxUfYXwCBucedthyN2_0gfiaXO2wp/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
