### ISSUE TITLE
23/04/2023: Xây dựng thông tin các rủi ro về giao tiếp giữa các bên liên quan cho phần rủi ro về quản lý

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#112]

**Comment by NoahSavant** [comment]
Hoàn thành task 6
Link document: https://docs.google.com/document/d/1xraAbi6CQoxIsMRyj7a_BRwDBXLBs-16/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
