### ISSUE TITLE
24/04/2023: Tổng hợp và hoàn thiện file quản lý rủi ro

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#113]

**Comment by NoahSavant** [comment]
Hoàn thành task 7
Link document: https://docs.google.com/document/d/1tQeuZ-l2nN501fmMj1wGkEChtE5kW23x/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
