### ISSUE TITLE
17/03/2023: Tìm hiểu và test API lấy thông tin chi tiết của project

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#12]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task.
Link document: https://docs.google.com/document/d/13Lbutjh7zdFmGTxXdT4ENjIYQvuGNfRhB-y0kjKUVD0/edit?usp=sharing
