### ISSUE TITLE
18/03/2023: Tìm hiểu và test API xoá project khỏi DB, các file liên quan

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#14]

**Comment by NoahSavant** [comment]
Hoàn thành task 5
Link document: https://docs.google.com/document/d/126r0fZ-Oxd85OroEX1Cv5ugkfPyPMSim/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
