### ISSUE TITLE
18/03/2023: Tìm hiểu và test API duplicate project

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#15]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task.
Link document: https://docs.google.com/document/d/1OlfA7s4BLtYNKCcOBhvw5bqHVWOf9BGFFVnBAuIvd9Q/edit?usp=sharing
