### ISSUE TITLE
19/03/2023: Tìm hiểu và test API upload custom preview thumbnail

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#17]

**Comment by NoahSavant** [comment]
Hoàn thành task 6
Link document: https://docs.google.com/document/d/1rA8Q3qjjoKLhrP2-xZ8R6TNPNDDeM4mI/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
