### ISSUE TITLE
14/03/2022: Tìm hiểu framework Flask

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#2]

**Comment by NoahSavant** [comment]
Hoàn thành task 1
Link document: https://docs.google.com/document/d/1Z7v_gDQe1hk_uOPsLOgFU-lLEdw5z88P/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
