### ISSUE TITLE
20/03/2023: Tìm hiểu và test API tạo preview thumbnail

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#20]

**Comment by NoahSavant** [comment]
Hoàn thành task 7
Link document: https://docs.google.com/document/d/10A7JtFqAgXqwVz4vNg2bm5FTuJKgQ9K0/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
