### ISSUE TITLE
20/03/2023: Tìm hiểu và test API lấy video file 

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#21]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task.
Link document: https://docs.google.com/document/d/1DtL2uvdqZ2y5Bb3uKnrUW6ZoIxlwqpnPad5d9CjdWxo/edit?usp=sharing
