### ISSUE TITLE
21/03/2023: Đặc tả usecase liệt kê các project hiện có

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#24]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1qhpMcAOwvQyGDxWgcXgEbxLV6MpnaBBb2uoiLYLdszM/edit?usp=share_link
