### ISSUE TITLE
21/03/2023: Đặc tả usecase lấy thông tin project cụ thể

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#25]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1hF9L6cION7ut6MAAdkv09NaXvgoIk3-3/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
