### ISSUE TITLE
22/03/2023: Đặc tả usecase nhân đôi project

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#27]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1lcQ42Qmo-BfQi5F2F24gtUQFpaRxyOX1/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
