### ISSUE TITLE
23/03/2023: Đặc tả usecase chuyển độ phân giải video

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#30]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1i_VDNMO1ms9F0nbrNpuLEQAT2HiF92r-/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
