### ISSUE TITLE
24/03/2023: Đặc tả usecase chụp hình thu nhỏ cho timeline

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#32]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1_yatwbHz7NUlAvpqUjOWjpbVWya4xzGJ6Wa0b_t5i-E/edit?usp=share_link
