### ISSUE TITLE
24/03/2023: Đặc tả usecase chụp hình thu nhỏ để xem trước ở một vị trí nhất định của video, với các thông số cắt và xoay video tùy chọn

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#33]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1fP1578bq6pwWzODr-_wQpWrFhXFfjhGG/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
