### ISSUE TITLE
25/03/2023: Đặc tả usecase lấy các file thumbnail

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#35]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1Ep6cgxjsfrgEaHJcz1Dh3vqzmBbdgU5-EVRjRcli7JM/edit?usp=share_link
