### ISSUE TITLE
25/03/2023: Đặc tả usecase lấy video file

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#36]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1dyxVpOma5jIqz68F55CGLSrTYaTOdH7d/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
