### ISSUE TITLE
26/03/2023: Mô tả bảng metadata trong CSDL

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#39]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/1V2lYNPrkZyuORrf_LTNMONbJBKLIHdSn/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
