### ISSUE TITLE
27/03/2023: Mô tả bảng preview trong CSDL

### ISSUE THREAD

**Issue by NoahSavant** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#42]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/19_9aMy_LXnQN1QMq_zKuG0fz4BPRG5AH/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
