### ISSUE TITLE
28/03/2023: Vẽ activity diagram cho chức năng liệt kê các project hiện có

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#45]

**Comment by TranMinhMan040702** [comment]
- Hoàn hành task
- Link document: https://docs.google.com/document/d/1BOsAyUciLlo7bXFWqJOS2WS8ingLG1VmQmXVs7hnu_c/edit?usp=share_link
