### ISSUE TITLE
28/03/2023: Vẽ activity diagram tạo project

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#47]

**Comment by NoahSavant** [comment]
Hoàn thành task 1
Link document: https://docs.google.com/document/d/1JVccFU2xKzZTWUFsZnVrYW1hKbZGW4lC/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
