### ISSUE TITLE
15/03/2023: Tìm hiểu MongoDB và cài đặt MongoDB

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#5]

**Comment by NoahSavant** [comment]
Hoàn thành task 2
Link document: https://docs.google.com/document/d/1ZSKLmtGjNe1xcz28gTGDcREp9PjQk9X1/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
