### ISSUE TITLE
29/03/2023: Vẽ activity chức năng nhân đôi project

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#52]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/18riAmplUbvQijB1lKPpjoFtW4EABBN-O/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
