### ISSUE TITLE
30/03/2023: Vẽ activity chức năng chuyển độ phân giải video

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#53]

**Comment by NMS1010** [comment]
Hoàn thành Task
Link document: https://docs.google.com/document/d/1PHpBvzCP3hyMWXFu_xROQphu7u9to_QS/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
