### ISSUE TITLE
01/04/2023: Vẽ activity chức năng lấy video file

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#55]

**Comment by NMS1010** [comment]
Hoàn thành Task
Link document: https://docs.google.com/document/d/1Jha9SFem9M5Cnx1syquex18o20by4_HR/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
