### ISSUE TITLE
29/03/2023: Tìm hiểu các phụ lục (Appendix A, B, C) của dự án

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#56]

**Comment by NoahSavant** [comment]
Hoàn thành task 2
Link document: https://docs.google.com/document/d/1tlEbG6CL5bacPUIKkwOJESBM1NCVgjtC/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
