### ISSUE TITLE
30/03/2023: Vẽ activity chức năng cắt nội dung video

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#57]

**Comment by NoahSavant** [comment]
Hoàn thành task 3
Link document: https://docs.google.com/document/d/1MyAkln6vqvceFefXDQ9apEagB_i3pNDV/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
