### ISSUE TITLE
31/03/2023: Vẽ activity chức năng cắt khung ảnh video

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#58]

**Comment by NoahSavant** [comment]
Hoàn thành task 4
Link document: https://docs.google.com/document/d/1jDWWOXxfoLFd45zuHXlbse8n89dF4N9g/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
