### ISSUE TITLE
01/04/2023: Vẽ activity chức năng tải lên hình ảnh có sẳn để tạo preview thumbnail

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#59]

**Comment by NoahSavant** [comment]
Hoàn thành task 5
Link document: https://docs.google.com/document/d/191BGxlm7mFe0dE1S1pYdB6cuj-bBqG_l/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
