### ISSUE TITLE
16/03/2023: Tìm hiểu cấu trúc thư mục project mẫu

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#6]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task.
Link document: https://docs.google.com/document/d/1XZotpe4Z-aFVMpSCe1TzUFfOsx8qLLZAODedDXXOJWY/edit?usp=sharing
