### ISSUE TITLE
02/04/2023: Tìm hiểu Overall Description của SRS

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#62]

**Comment by NMS1010** [comment]
Hoàn thành Task
Link document: https://docs.google.com/document/d/13dSIF5dvtxe2pTtiRTjmQ9yipSQr8D8Z/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
