### ISSUE TITLE
03/04/2023: Tìm hiểu System Features của SRS

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#63]

**Comment by NMS1010** [comment]
Hoàn thành Task
Link document: https://docs.google.com/document/d/12unBoZSAVm7ZdYiSW9OJgIsuegtS85EJ/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
