### ISSUE TITLE
02/04/2023: Tìm hiểu Other Nonfunctional Requirements của SRS

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#64]

**Comment by NoahSavant** [comment]
Hoàn thành task 6
Link document: https://docs.google.com/document/d/1ngeB4KtaJB9E-1xVLXzOY_1nJZiRjtIc/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
