### ISSUE TITLE
03/04/2023: Tìm hiểu Other Requirements của SRS

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#65]

**Comment by NoahSavant** [comment]
Hoàn thành task 7
Link document: https://docs.google.com/document/d/18KFImbZwFS3HFQn-v65ckjKHAS3tbZMQ/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
