### ISSUE TITLE
16/03/2023: Chạy project mẫu

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#8]

**Comment by NoahSavant** [comment]
Hoàn thành task 3:
Link document: https://docs.google.com/document/d/1kVJXIp5be28_lj9MjRvrRHhJRU0962Zs/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
