### ISSUE TITLE
15/03/2023: Tìm hiểu RabbitMQ và cài đặt RabbitMQ

### ISSUE THREAD

**Issue by NMS1010** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#9]

**Comment by TranMinhMan040702** [comment]
Hoàn thành task.
Link document: https://docs.google.com/document/d/1Obb39vHexMMOlWQKwEriB3-f0MjIKEogjm5FXziMLGY/edit?usp=sharing
