### ISSUE TITLE
18/04/2023: Tìm hiểu cú pháp tạo Dockerfile

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#93]

**Comment by NoahSavant** [comment]
Hoàn thành task 1
Link document: https://docs.google.com/document/d/1601SM_n_7HkTqmDEgvZZKVB05LUoRfUT/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
