### ISSUE TITLE
19/04/2023: Viết Dockerfile

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#94]

**Comment by NoahSavant** [comment]
Hoàn thành task 2
Link document: https://docs.google.com/document/d/1uxSRzqFtP5ZQwweYjw63MTNRhQed-daJ/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
