### ISSUE TITLE
20/04/2023: Viết step cài đặt và chạy RabbitMQ service

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#95]

**Comment by NoahSavant** [comment]
Hoàn thành task 3
Link document: https://docs.google.com/document/d/1B6f0F8xxLn-nVTvhbx6iQOkHgquQ1oe4/edit?usp=sharing&ouid=103454097970757228267&rtpof=true&sd=true
