### ISSUE TITLE
21/04/2023: Viết step cài đặt project và chạy local test

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#96]

**Comment by NoahSavant** [comment]
Hoàn thành task 4
Link document: https://docs.google.com/document/d/1ligqh4QvOBsu5Evd_HSLG9XYTHcZ-ymRec8nZhpv4Y4/edit?usp=sharing
