### ISSUE TITLE
18/04/2023: Tìm hiểu docker compose

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#97]

**Comment by NMS1010** [comment]
Hoàn thành task
Linh document: https://docs.google.com/document/d/1VMZmXQ0CgGbc2jdmRqjwGFB-HRZ-O2jI/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
