### ISSUE TITLE
19/04/2023: Viết docker compose

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#98]

**Comment by NMS1010** [comment]
Hoàn thành task
Linh document: https://docs.google.com/document/d/1Jx7XbnCfEPcAMqpbuNCpapBJJQ1vyLuk/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
