### ISSUE TITLE
20/04/2023: Viết step deploy project lên EC2

### ISSUE THREAD

**Issue by TranMinhMan040702** [NMS1010/Video-Proccessing-and-Storaging-Service_Nhom23_Detai15#99]

**Comment by NMS1010** [comment]
Hoàn thành task
Link document: https://docs.google.com/document/d/17zAIZEZ6tTrEmsjIOucvd2F7UfKWDanp/edit?usp=share_link&ouid=106272368456595085295&rtpof=true&sd=true
